# Site settings
title: Brian Taubman for Lakewood Municipal Court Judge
email: your-email@domain.com
description: "It's time for new leadership this November. Vote for Brian and make your plea for common sense."
baseurl: ""
url: "http://taubmanforjudge.com"
logo: "taubman-logo.png"
bio_photo: "taubman-bio.jpg"
default_bg: "main.jpg"
subpage_bg: "subpage.jpg"
short_bio: "Brian loves spending time with his two dogs at the Metroparks and Lakewood Dog Park. He also enjoys eating at local restaurants and "

# Build settings
markdown: kramdown
permalink: pretty

kramdown: 
  input: GFM

# Links to include in site navigation
links:
  - title: About
    url: /about
  - title: What Brian Stands For
    url: /what-brian-stands-for
  - title: Volunteer
    url: /volunteer
  - title: Donate
    url: /donate
  - title: Contact
    url: /contact

# Social media links
social:
  twitter:  Taubmanforjudge
  facebook: taubmanforjudge2015
  linkedin: 
  google_plus:
  instagram: 